### ISSUE TITLE
Peristaltic pump

### ISSUE THREAD

**Issue by Thomas-Bradford** [AguaClara/Dissolved-Gas#1]
@mailemccann The Dissolved Gas subteam will need a peristaltic pump for our prototype apparatus to remove excess dissolved air from influent water. Do you know if the RAM Pump subteam's peristaltic pump would be available for use?

**Comment by mailemccann** [comment]
I'm looping in @AlyciaStorch . However, Ram Pump hasn't been using a peristaltic pump, we use a sump pump in experiments. If there's one on the lab bench going unused (I forget) I'm sure you can use it.

**Comment by Thomas-Bradford** [comment]
Thanks!
