### ISSUE TITLE
Bubble nucleation in sand beds- Troubleshooting El PODA

### ISSUE THREAD

**Issue by juanchon998** [AguaClara/Dissolved-Gas#3]
Hello Dissolved Gas team!

I see that you have gathered literature on bubble nucleation... Does that include bubble nucleation in sand beds? I ask because currently there's a big problem with dissolved air in the filters of the El PODA plant in Nicaragua causing _a lot_ of head loss. [You can see that the sed tank looks like it has soda in it!](https://photos.app.goo.gl/RZDZXzTFk7b74w6k9)

[Here](https://photos.app.goo.gl/bEg6XEdP6sgPqpcK8) are pictures and videos of the plant if you're interested.

**Comment by kab394** [comment]
Hi Juan,

Yes, it does include nucleation in sand beds! Our subteam's goal is to maximize bubble growth before the water enters the plant using a fluidized bed composed of sand and water. This way, bubbles will escape early on and prevent any problems like the ones you see at the El PODA plant.

Thank you for the pictures and videos! These will definitely help illustrate the issue that we are working to resolve.

**Comment by juanchon998** [comment]
Awesome stuff, I wish you guys luck then! 

Don't hesitate to reach out if you need any field info. I'll look into your reports as you produce them this semester!

**Comment by isaacsinger8** [comment]
Thanks Juan!  We really appreciate it.

Best,
Isaac Singer
