### ISSUE TITLE
600RPM Peristaltic Pump 

### ISSUE THREAD

**Issue by Thomas-Bradford** [AguaClara/Dissolved-Gas#4]
@monroews 

Our current apparatus may require a 600RPM capacity peristaltic pump; do you know if there is one available for the subteam's use?

Thanks!

**Comment by monroews** [comment]
Check the pump cabinet. Then ask on slack. If no luck, perhaps I need to
buy one. Check quickly and get back to me.

**Comment by monroews** [comment]
There was a 600 rpm pump in the pump cabinet. I checked it out and it didn't work. So I threw it away. Not sure why there was a broken pump without any indication that it wasn't working in our pump cabinet.
I ordered 3 600 rpm pumps this morning. It could take a week for them to arrive. In the meantime the only option I can think of is connecting 4 pump heads in parallel on a 100 rpm pump.

**Comment by Thomas-Bradford** [comment]
Thank you for your help & advice - we'll consider using that set-up in the meantime while we wait for the pumps to arrive. I apologize if I miscommunicated / didn't reply timely enough; we (the subteam) had planned on following up with your message today, after leaving the Slack question open for a day.
